Repository nevexo-technologies/real, pull requests merged in 2022-11, with the labels that each got.

#12 Created API routes for highschool
  apps/formular/package.json
  apps/rezultate/package.json
  apps/rezultate/pages/api/hello.ts
  apps/rezultate/pages/api/hs/[highschool].ts
  apps/rezultate/pages/api/hs/index.ts
  apps/rezultate/tsconfig.json
  packages/database/src/index.ts
Labels: backend

#14 Adaugare landing page si pagina detalii licee
  apps/rezultate/components/Header.tsx
  apps/rezultate/components/Layout.tsx
  apps/rezultate/helpers/createMUITheme.ts
  apps/rezultate/package.json
  apps/rezultate/pages/[highschool].tsx
  apps/rezultate/pages/_app.tsx
  apps/rezultate/pages/index.tsx
  apps/rezultate/public/background-dark.png
  apps/rezultate/public/background-light.png
  apps/rezultate/public/logo.png
  apps/rezultate/public/logo.webp
  apps/rezultate/styles/globals.css
  yarn.lock
Labels: frontend

#15 Rezultate/highschool api
  apps/rezultate/helpers/hsIndexes.ts
  apps/rezultate/pages/api/hs/[highschool].ts
  package-lock.json
  packages/database/package.json
  yarn.lock
Labels: enhancement, backend

#19 Rezultate/highschool api
  apps/rezultate/helpers/getHsMetrics.ts
  apps/rezultate/helpers/rateLimit.ts
  apps/rezultate/next.config.js
  apps/rezultate/package.json
  apps/rezultate/pages/api/hello.ts
  apps/rezultate/pages/api/hs/[highschool].ts
  apps/rezultate/pages/api/hs/index.ts
  package-lock.json
  yarn.lock
Labels: enhancement, backend
